#!/bin/bash
# Server Demise Pipeline - Documentation Access Info

echo "🌐 Server Demise Pipeline Documentation"
echo "============================================="
echo ""
echo "📋 Main Documentation:"
echo "   🔗 http://localhost:8093"
echo "   🌍 http://$(hostname -I | awk '{print $1}'):8093"
echo ""
echo "📡 API Service:"
echo "   🔗 http://localhost:8082"
echo "   🌍 http://$(hostname -I | awk '{print $1}'):8082"
echo "   📖 API Docs: http://localhost:8082/docs"
echo ""
echo "📁 Available Documentation:"
echo "   📄 Main (HTML): http://localhost:8093/"
echo "   📄 README: http://localhost:8093/README.md"
echo "   📄 Quick Guide: http://localhost:8093/QUICK_REFERENCE.md"
echo ""
echo "🔧 Management:"
echo "   🛑 Stop docs server: pkill -f 'PORT = 8093'"
echo "   📊 Check ports: netstat -tulpn | grep -E '(8082|8093)'"
echo ""
echo "✅ Both servers are running and accessible!"
echo "🌍 Share the IP:8093 URL with others for documentation access"